### ISSUE TITLE
Sourcesets not correctly set (>0.2.5)

### ISSUE THREAD

**Issue by rnorth** [revolut-engineering/jooq-plugin#9] opened 2020-05-21 14:58 UTC
On a fairly new codebase where I'm using this plugin, I've encountered what seems like a regression in versions greater than 0.2.5.

It would appear that after this version the sourcesets and compileJava dependency on generateJooqClasses are no longer automatically set up correctly: what I've observed is:

* `generateJooqClasses` not being run at all in a normal build (e.g. `clean check`). _This can be worked around by adding `compileJava.dependsOn(generateJooqClasses)` to the build script._

Following that workaround, it's still not good news:
* Compilation failures in `main` code that depends on any generated classes
* IDE no longer detects the `build/generated-jooq` directory as a source directory

I've not had time to dig into why this is happening, but for me both of the following workarounds work:

* Stick with v0.2.5 of the plugin
or
* Add the following to `build.gradle`:

```
compileJava.dependsOn(generateJooqClasses)

sourceSets {
    jooq {
        java {
            srcDirs "${buildDir}/generated-jooq"
            compileClasspath += main.compileClasspath
            runtimeClasspath += main.runtimeClasspath
        }
    }
    main {
        java {
            compileClasspath += jooq.output
            runtimeClasspath += jooq.output
        }
    }
    test {
        java {
            compileClasspath += jooq.output
            runtimeClasspath += jooq.output
        }
    }
}
```

I can put together a repro example if you'd like, but before I do so, does anything spring to mind?

**Comment by adrianskrobaczrevolut** [comment] 2020-05-21 18:29
Hey @rnorth 🙂 
That's actually very interesting, because >0.2.5 are the versions where I actually fixed the ugly way we used to configure source sets 😅 https://github.com/revolut-engineering/jooq-plugin/commit/b12e6664ad0fdfeac673dfd86dc2e0de10df0e2f#diff-83a8e2a543bc56687e2b75ec62457ef6R93
One thing that crosses my mind is that on previous versions the plugin was automatically applying the `java` plugin now it's not doing that anymore and let users apply either that or Kotlin plugin depending on needs. Could you try explicitly applying `java` plugin to the project ? If that doesn't help it would be really helpful if you could post some simple setup that reproduces the problem.

**Comment by rnorth** [comment] 2020-05-21 19:36
Ah, maybe I've hit an edge case against the new way of doing things then!

I'll create an example repository: unfortunately I already have the `java` plugin applied, so it must be some other nuance.

Thanks for getting back to me quickly!

**Comment by rnorth** [comment] 2020-05-21 20:26
Quick repository to demonstrate this:

https://github.com/rnorth/jooq-plugin-issue9-repro

* Master branch uses v0.3.3 of the plugin along with manually-added sourcesets. Compiles OK.
* [This branch](https://github.com/rnorth/jooq-plugin-issue9-repro/tree/without-manual-sourcesets) uses v0.3.3 without the manual sourcesets. Compilation of code in `main` fails.
* [This branch](https://github.com/rnorth/jooq-plugin-issue9-repro/tree/downgrade-jooq-plugin) downgrades the plugin to v0.2.5 and removes the manual sourcesets. Compiles OK.

I hope this helps - if you spot anything I'm doing wrong please do let me know.

**Comment by adrianskrobaczrevolut** [comment] 2020-05-22 13:32
Thanks for the repo it was helpful 👍 I did some digging and I found what is the problem. Current implementation of the plugin assumes that the Java plugin will be applied before the jooq plugin and seems like it's not the case for this project. What bothers me is that we actually have the test case for Java project compilation [here](https://github.com/revolut-engineering/jooq-plugin/blob/master/src/test/groovy/JooqDockerPluginSpec.groovy#L793), that passes but when I copy exact same setup as a standalone project it fails the same way your reporo exmple 🤔 I'll do some more digging later maybe I'll be able to reproduce the problem with the test somehow, but anyways I'll fix the problem in the next release. Unfortunately until that you will have to stick to the workaround you proposed or to older version or in the more complex setups with subprojects it seems to work just fine. Thanks for raising the issue and I'll keep you posted here once I fix it 👍

**Comment by adrianskrobaczrevolut** [comment] 2020-06-16 15:38
@rnorth @victorlopezsalazar should be now fixed in latest `0.3.4` version. Let me know if it works for you guys 🙂

**Comment by rnorth** [comment] 2020-06-16 16:07
Great, thanks so much! I’ll give it a try and let you know.

**Comment by victorlopezsalazar** [comment] 2020-06-17 15:56
In my case, I got the following stacktrace:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateJooqClasses'.
   ...

Caused by: java.lang.NoSuchMethodError: org.flywaydb.core.api.configuration.FluentConfiguration.defaultSchema(Ljava/lang/String;)Lorg/flywaydb/core/api/configuration/FluentConfiguration;
        at com.revolut.jooq.GenerateJooqClassesTask.migrateDb(GenerateJooqClassesTask.kt:165)
        at com.revolut.jooq.GenerateJooqClassesTask.access$migrateDb(GenerateJooqClassesTask.kt:23)
        at com.revolut.jooq.GenerateJooqClassesTask$generateClasses$$inlined$use$lambda$1.execute(GenerateJooqClassesTask.kt:153)
        at com.revolut.jooq.GenerateJooqClassesTask$generateClasses$$inlined$use$lambda$1.execute(GenerateJooqClassesTask.kt:23)
        at com.revolut.jooq.Docker.runInContainer(Docker.kt:38)
        at com.revolut.jooq.GenerateJooqClassesTask.generateClasses(GenerateJooqClassesTask.kt:152)

```

the config for the task is the following:

```
generateJooqClasses {
    schemas = ["my_schema"]
    basePackageName = "package"
    customizeGenerator {
        generate = new Generate()
                    .withRelations(true)
                    .withDeprecated(false)
                    .withRecords(true)
                    .withImmutablePojos(true)
                    .withFluentSetters(true)
                    .withJavaTimeTypes(false)
                    .withPojosEqualsAndHashCode(true)
    }
}
```

worth to mention that I also have the configuration to replace the flyway version enabled:

```
resolutionStrategy {
            dependencySubstitution {
                substitute(module("org.flywaydb:flyway-core"))
                        .with(module("org.flywaydb:flyway-core:5.2.4"))
            }
        }
```
I will play around with configs later when I got a little time to do it.

**Comment by rnorth** [comment] 2020-06-19 14:48
I’ve upgraded to 0.3.4 and removed the workarounds, and it seems to work perfectly! Thanks for solving the problem @adrianskrobaczrevolut!

**Closed** 2021-02-23 13:47 UTC
Labels: bug
